name: Convert README.md to HTML

on:
  push:
    branches:
      - main  # یا branch اصلی شما

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ۱. چک کردن کد
    - uses: actions/checkout@v3

    # ۲. نصب Ruby و Jekyll
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install Bundler and Jekyll
      run: |
        gem install bundler
        gem install jekyll

    # ۳. ساخت سایت با Jekyll
    - name: Build Jekyll site
      run: |
        jekyll new temp-site
        cp README.md temp-site/
        cd temp-site
        # اضافه کردن Front Matter به README.md
        echo -e "---\nlayout: default\ntitle: README\n---\n" | cat - README.md > README_with_frontmatter.md
        mv README_with_frontmatter.md README.md
        jekyll build

    # ۴. Commit و Push فایل HTML به repo (اختیاری)
    - name: Commit generated HTML
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add temp-site/_site/README.html
        git commit -m "Add generated README HTML" || echo "No changes to commit"
        git push
